Update ASM version to 9.6 to support JDK 22 class files
This should fix a JDK 22-ea issue with the test infrastructure:

```
java.lang.IllegalArgumentException: Unsupported class file major version 67
	at com.google.turbine.lower.LowerIntegrationTest.test(LowerIntegrationTest.java:432)
```

The javac flag `--enable-preview` is deliberately only supported for the latest language level, so testing preview features (like string templates) on JDK 22 requires using JDK 22 class files.

PiperOrigin-RevId: 602464584