Don't read `<clinit>`s from class files
This was causing an error when checking required annotation elements for
annotations with `<clinit>`s read from bytecode:

```
error: missing required annotation argument: <clinit>
@Foo
```

https://github.com/bazelbuild/bazel/issues/13144

PiperOrigin-RevId: 360553027